import assert from 'node:assert/strict';

export async function checkStrategyUI(tab, browser) {
  const ui = tab.playwright;
  const viewport = await browser.capabilities.get('viewport');
  await viewport.set({ width: 1280, height: 900 });
  await ui.getByRole('button', { name: 'Threads', exact: true }).press('Enter');
  await ui.getByRole('combobox', { name: 'Agent mode', exact: true }).selectOption('BACKTEST');
  await ui.getByRole('heading', { name: 'Backtest', exact: true }).waitFor({ state: 'visible' });
  assert.equal(await ui.getByLabel('Instrument', { exact: true }).count(), 1);
  assert.equal(await ui.getByLabel('Dataset', { exact: true }).count(), 1);
  await ui.getByRole('button', { name: 'Open Strategies from BACKTEST context', exact: true }).press('Enter');
  await ui.getByRole('heading', { name: 'Strategies', exact: true }).waitFor({ state: 'visible' });
  await ui.getByText('Opened from BACKTEST context', { exact: true }).waitFor({ state: 'visible' });
  await ui.getByRole('button', { name: 'Strategies', exact: true }).press('Enter');
  await ui.getByRole('heading', { name: 'Strategies', exact: true }).waitFor({ state: 'visible' });
  await ui.getByRole('button', { name: 'Save version', exact: true }).press('Enter');
  await ui.getByText(/Selected .* · v1 · sha256:/).waitFor({ state: 'visible' });
  await ui.getByRole('button', { name: 'Threads', exact: true }).press('Enter');
  await ui.getByRole('combobox', { name: 'Agent mode', exact: true }).selectOption('BACKTEST');
  const savedBacktestVersion = ui.getByRole('combobox', { name: 'Saved strategy version', exact: true });
  await savedBacktestVersion.selectOption({ index: 1 });
  const threadBacktestScenario = ui.getByRole('combobox', { name: 'Backtest integration scenario', exact: true });
  const threadBacktestRun = ui.getByRole('button', { name: 'Run backtest', exact: true });
  const threadInstrument = ui.getByLabel('Instrument', { exact: false });
  await threadInstrument.press('ControlOrMeta+A');
  await threadInstrument.press('Backspace');
  await threadBacktestRun.press('Enter');
  await ui.getByText('Enter an instrument.', { exact: true }).waitFor({ state: 'visible' });
  assert.equal(await ui.getByLabel('Instrument', { exact: false }).getAttribute('aria-invalid'), 'true');
  await threadInstrument.fill('equity:US:AAPL');
  await threadBacktestScenario.selectOption('FAILURE');
  await threadBacktestRun.press('Enter');
  await ui.getByText('FAILED', { exact: true }).waitFor({ state: 'visible' });
  await ui.getByText('BACKTEST_FIXTURE_FAILED:', { exact: false }).waitFor({ state: 'visible' });
  await ui.getByRole('heading', { name: 'Frozen configuration', exact: true }).waitFor({ state: 'visible' });
  await ui.getByRole('button', { name: 'Strategies', exact: true }).press('Enter');
  await ui.getByRole('heading', { name: 'Strategies', exact: true }).waitFor({ state: 'visible' });
  await ui.getByRole('button', { name: /My strategy/ }).press('Enter');
  const scenario = ui.getByRole('combobox', { name: 'Integration scenario', exact: true });
  const run = ui.getByRole('button', { name: 'Run selected version', exact: true });
  await scenario.selectOption('SUCCESS');
  await run.press('Enter');
  await ui.getByText('COMPLETED', { exact: true }).waitFor({ state: 'visible' });
  assert.equal(await ui.getByText('HOLD', { exact: true }).count(), 1);
  assert.equal(await ui.getByRole('button', { name: /Trade|Approve|Reserve/ }).count(), 0);
  assert.equal(await ui.locator('.strategy-result').getAttribute('aria-live'), 'polite');
  await scenario.selectOption('FAILURE');
  await run.press('Enter');
  await ui.getByText('FAILED', { exact: true }).waitFor({ state: 'visible' });
  const retry = ui.getByRole('button', { name: 'Retry run', exact: true });
  await retry.press('Enter');
  await ui.getByText('FAILED', { exact: true }).waitFor({ state: 'visible' });
  assert.equal(await ui.evaluate(() => document.activeElement?.textContent?.trim()), 'Retry run');
  await scenario.selectOption('CANCELLED');
  await run.press('Enter');
  await ui.getByText('RUNNING', { exact: true }).waitFor({ state: 'visible' });
  await ui.getByRole('button', { name: 'Cancel run', exact: true }).press('Enter');
  await ui.getByText('CANCELLED', { exact: true }).waitFor({ state: 'visible' });
  assert.equal(await ui.evaluate(() => document.activeElement?.textContent?.trim()), 'Retry run');
  await ui.getByRole('heading', { name: 'Backtest', exact: true }).waitFor({ state: 'visible' });
  await ui.getByLabel('Bar interval', { exact: true }).selectOption('1d');
  await ui.getByLabel('Starting cash', { exact: true }).fill('100000');
  await ui.getByLabel('Commission', { exact: true }).fill('0');
  await ui.getByLabel('Slippage', { exact: true }).fill('0');
  const backtestScenario = ui.getByRole('combobox', { name: 'Backtest integration scenario', exact: true });
  const backtestRun = ui.getByRole('button', { name: 'Run backtest', exact: true });
  await backtestScenario.selectOption('FAILURE');
  await backtestRun.press('Enter');
  await ui.getByText('FAILED', { exact: true }).waitFor({ state: 'visible' });
  await ui.getByText('BACKTEST_FIXTURE_FAILED:', { exact: false }).waitFor({ state: 'visible' });
  const firstBacktestRun = /Run ([0-9a-f-]+)/.exec(await ui.locator('.strategy-result').last().innerText())?.[1];
  await ui.getByRole('button', { name: 'Retry backtest', exact: true }).press('Enter');
  await ui.getByText('FAILED', { exact: true }).waitFor({ state: 'visible' });
  const retriedBacktestRun = /Run ([0-9a-f-]+)/.exec(await ui.locator('.strategy-result').last().innerText())?.[1];
  assert.ok(firstBacktestRun && retriedBacktestRun && firstBacktestRun !== retriedBacktestRun, 'Backtest retry must create a new run ID');
  await backtestScenario.selectOption('CANCELLED');
  await backtestRun.press('Enter');
  await ui.getByText('RUNNING', { exact: true }).waitFor({ state: 'visible' });
  await ui.getByRole('button', { name: 'Cancel backtest', exact: true }).press('Enter');
  await ui.getByText('CANCELLED', { exact: true }).waitFor({ state: 'visible' });
  assert.equal(await ui.evaluate(() => document.activeElement?.textContent?.trim()), 'Retry backtest');
  for (const width of [768, 390]) {
    await viewport.set({ width, height: 900 });
    const size = await ui.evaluate(() => ({ width: document.documentElement.clientWidth, scroll: document.documentElement.scrollWidth }));
    assert.ok(size.scroll <= size.width, `Strategy page overflow at ${width}px: ${JSON.stringify(size)}`);
  }
  return ['Research/Backtest context opens Strategies with preserved context', 'strategy draft saved as immutable version', 'strategy and backtest success/failure/retry/cancel states preserve keyboard focus', 'fixture run returned signal-only HOLD', 'strategy surface stayed within 768px/390px viewport'];
}
